:: AD input includes both the training velocity and weight anomaly data
for /D %%p IN ("Input\AD\Data\*") DO (
	del /s /f /q %%p\*.*
	for /f %%f in ('dir /ad /b %%p') do rd /s /q %%p\%%f
	rmdir "%%p" /s /q
)
del /F /Q Input\AD\Data\*
:: AD output involves the windows that will be used as input for ELE
del /F /Q Output\AD\Data\*

:: ELE only cointans the effective data to be used in subsequent steps, i.e., the targeted anomaly
del /F /Q Input\ELE\Data\Training\*
del /F /Q Input\ELE\Data\Test\*
:: ELE output consists of the training and test event logs to be used later
del /F /Q Output\ELE\EventLog\*

:: PD input takes the training event log generated by ELE
del /F /Q Input\PD\EventLog\*
:: PD outputs a Petri net in terms of its structure and timing distributions, and the timing statistics
del /F /Q Output\PD\PetriNet\*
del /F /Q Output\PD\Timing\*

:: S input involves the clustering parameters obtained formerly and the Petri net (structure + timing distributions)
del /F /Q Input\S\Clustering\*
del /F /Q Input\S\PetriNet\*
:: S output collects the simulated time series and the timing statistics
del /F /Q Output\S\Data\*
del /F /Q Output\S\Timing\*



